### PR TITLE
Remove tasks related to Ubuntu 14.04

### PR DESCRIPTION
**Pull request by scollazo**
Connects to https://github.com/archivematica/Issues/issues/427

### CODE REVIEW

**Review by mamedin — CHANGES_REQUESTED** [review]
Hi Santi, this branch works fine for AM qa/1.x deploys.

When using this branch for AM v1.8.1 deploy, I got the error:

```
fatal: [mamedin-es-centos]: FAILED! => {"changed": false, "cmd": "./manage.py migrate --noinput --pythonpath=/usr/lib/archivematica/archivematicaCommon", "failed": true, "msg": "\n:stderr: Traceback (most recent call last):
\n  File \"./manage.py\", line 10, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute_from_command_line\n    utility.execute()\n  File \"/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py\", line 346, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py\", line 394, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File \"/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py\", line 445, in execute\n    output = self.handle(*args, **options)\n  File \"/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 93, in handle\n    executor = MigrationExecutor(connection, self.migration_progress_callback)\n  File \"/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 19, in __init__\n    self.loader = MigrationLoader(self.connection)\n  File \"/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 47, in __init__\n    self.build_graph()\n  File \"/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 314, in build_graph\n    parent = self.check_key(parent, key[0])\n 
 File \"/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 175, in check_key\n    
 raise ValueError(\"Dependency on app with no migrations: %s\" % key[0])\nValueError: Dependency on app with no migrations: fpr\n", "path": "/usr/share/archivematica/virtualenvs/archivematica-dashboard/bin:/sbin:/bin:/usr/sbin:/usr/bin", "state": "absent", "syspath": ["/tmp/ansible_bA0tAs", "/tmp/ansible_bA0tAs/ansible_modlib.zip", "/tmp/ansible_bA0tAs/ansible_modlib.zip", "/usr/lib64/python27.zip", "/usr/lib64/python2.7", "/usr/lib64/python2.7/plat-linux2", "/usr/lib64/python2.7/lib-tk", "/usr/lib64/python2.7/lib-old", "/usr/lib64/python2.7/lib-dynload", "/usr/lib64/python2.7/site-packages", "/usr/lib/python2.7/site-packages"]}
```

 And running the dashboard migration:

 ```
[artefactual@mamedin-es-centos ~]$ sudo -u archivematica bash -c " \
> set -a -e -x
> source /etc/sysconfig/archivematica-dashboard
> cd /usr/share/archivematica/dashboard
> /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py migrate
> ";
+ source /etc/sysconfig/archivematica-dashboard
++ PYTHONPATH=/usr/lib/archivematica/archivematicaCommon:/usr/share/archivematica/dashboard
++ ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_ALLOWED_HOSTS='*'
++ ARCHIVEMATICA_DASHBOARD_SEARCH_ENABLED=yes
++ REQUEST_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
++ ARCHIVEMATICA_DASHBOARD_CLIENT_DATABASE=MCP
++ ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER=127.0.0.1:9200
++ DJANGO_SETTINGS_MODULE=settings.production
++ ARCHIVEMATICA_DASHBOARD_CLIENT_HOST=localhost
++ AM_GUNICORN_BIND=127.0.0.1:8002
++ ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_SECRET_KEY=CHANGE_ME_WITH_A_SECRET_KEY
++ ARCHIVEMATICA_DASHBOARD_CLIENT_PASSWORD=ja0Oghaiteik
++ ARCHIVEMATICA_DASHBOARD_CLIENT_USER=archivematica
+ cd /usr/share/archivematica/dashboard
+ /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/migrations/loader.py", line 314, in build_graph
    parent = self.check_key(parent, key[0])
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/migrations/loader.py", line 175, in check_key
    raise ValueError("Dependency on app with no migrations: %s" % key[0])
ValueError: Dependency on app with no migrations: fpr
```

I think the `pipeline-dbconf-migrate-1_4-to-1_5.yml` file is still needed for AM v1.8.x deploys.

**Comment by scollazo** [comment]
I'm investigating, that file it's not being, as ```archivematica_src_am_migrate_from_v1_4``` is set to ```false``` in https://github.com/artefactual-labs/ansible-archivematica-src/blob/stable/1.8.x/defaults/main.yml#L53

**Comment by mamedin** [comment]
You're right, the fault was because I was doing a downgrade from AM1.9 to AM1.8.1. 

After cleaning the system the AM18 deploy works fine.

**Review by mamedin — APPROVED** [review]
LGTM

**Pull request merged**
