### PR TITLE
Dependency fixes

### PR DESCRIPTION
**Pull request by sevein**
Related to artefactual/archivematica#398. You don't want to merge this as it is because the changes in that pull request are only available at qa/1.x at the moment - they haven't been ported to previous branches. Maybe we should backport that, or we figure a way to deal with it in this role?

### CODE REVIEW

**Comment by sevein** [comment]
I also made some cosmetic changes!

**Comment by hakamine** [comment]
Defined variables to deal with varying dependencies

**Comment by sevein** [comment]
That's a very good idea, @hakamine!

**Comment by sevein** [comment]
@hakamine and I agreed that it'd be best to have a text file inside the repo listing the dependencies, e.g. `requirements.ubuntu-trusty.txt` in `dashboard`, `MCPServer`, `MCPClient`... thoughts?

**Comment by sevein** [comment]
We'd have to make sure that the new requirements file is available in stable/1.4, qa/1.5 and qa/1.x. If this role is being used to deploy another branch it'd be necessary to make sure that it's been updated to include the requirements.

**Comment by Hwesta** [comment]
I'm inclined to put the package dependency list in ansible for now, since there's a lot of Archivematica dev branches that we want to deploy that wouldn't have the new packages file.  If we list os-level dependencies in ansible, I think it also makes it easier to use ansible to deploy to other systems (eg CentOS, with a different packages list).  I can be convinced otherwise.

:+1:

**Comment by sevein** [comment]
:+1:

**Comment by sevein** [comment]
Woohoo!

**Pull request merged**
