### PR TITLE
Add ansible vars for mysql configuration

### PR DESCRIPTION
**Pull request by scollazo**
Closes redmine#11913

### CODE REVIEW

**Comment by hakamine** [comment]
(Unless doing it could potentially break something) I think that it could be a good opportunity to remove the tasks that create the mysql database and user from the archivematica role and use instead the database role (like we do with the AtoM role: for example https://github.com/artefactual/deploy-pub/tree/master/playbooks/atom-xenial ). Thoughts?

**Comment by scollazo** [comment]
Ok, seems a good idea, I'll  remove the mysql user/db creation from am playbooks

**Review by sevein — CHANGES_REQUESTED** [review]
@hakamine do you want to take another look to this PR? Santi forgot to add a comment so we were not notified about the changes but it seems that your feedback has been addressed.

I also have a question for you @scollazo. I see that you've deleted `tasks/pipeline-dbconf-migrate-1_4-to-1_5.yml` as part of the commit `Don't create mysql database and user`. That was unexpected but I'm sure you have your reasons - should that be in a separate commit with a detailed description of why we're removing it?

**Comment by scollazo** [comment]
As the 1.7 playbooks bring a lot of changes , I thought that the sane way to upgrade from an old version, would be using the stable/1.6.x version of the playbooks to upgrade to 1.6, and the stable/1.7.x playbook for upgrades from 1.6 to 1.7

Having that upgrade path in mind, I thought about  ``tasks/pipeline-dbconf-migrate-1_4-to-1_5.yml`` as old/unused code that can be removed, instead of updated to be used with 1.7

I splitted the commit into it's own, as you suggests.

**Comment by hakamine** [comment]
Changes look good, but haven't tested. I see that the PR is still keeping the tasks that create and delete the MCP database in `pipeline-dbconf.yml` for resetting the db. I'd really prefer to completely remove all the tasks that create/delete databases in this role (as they probably belong to a database role not the AM role), but I understand that if we do this we will no longer be able to clear the database using this role, and this would probably break some current use cases.

**Comment by scollazo** [comment]
@sevein ping

**Comment by sevein** [comment]
So what's exactly the problem that the commit `Remove 1.4 and 1.5 migrations` is trying to solve? Its description reads:

> Systems coming from those releases **can** use the stable/1.6.x branch of this playbook for updating to 1.6 first.

I guess I'm still unclear if your commit is removing dead code or it's trying to make the role simpler at the cost of the complexity on the user side during upgrades. Thanks.

**Comment by scollazo** [comment]
I don't have an strong opinion on this, nor the time or the strengt to continue arguing.  I removed the commit of the 1.4 and 1.5 migrations and created #187.  I hope everything is ok now.

**Review by sevein — APPROVED** [review]

**Pull request merged**
