### PR TITLE
Load /etc/default/archivematica-<> in upstart

### PR DESCRIPTION
**Pull request by scollazo**
This is the default method to add env vars in xenial and centos

### CODE REVIEW

**Review by sevein — APPROVED** [review]
I haven't tested it but LGTM.

**Review by jhsimpson — APPROVED** [review]
:+1:

**Comment by scollazo** [comment]
Changed the ` $(cat /etc/default/archivematica-*)` and used ` $(grep -v ^# /etc/default/archivematica-*` , as upstart chokes with the "# Ansible managed" line

**Review by mamedin — APPROVED** [review]
Looks good to me

**Pull request merged**
