### PR TITLE
Clean-ups and sudo requirement change

### PR DESCRIPTION
**Pull request by sevein**
See the commit for more details: [f8470f5](https://github.com/artefactual-labs/ansible-role-archivematica-src/commit/f8470f5ba3a70413fc786145036a6326a5dac71b).

I recommend to review this PR browsing the whole tree instead of looking at the files, see [f8470f5](https://github.com/artefactual-labs/ansible-role-archivematica-src/tree/f8470f5ba3a70413fc786145036a6326a5dac71b).

**IMPORTANT**: from now on, this role expects you to invoke it with sudo, e.g.:
```yaml
---
- hosts: "server1"
  roles:
    - role: "archivematica-src"
      sudo: "yes"
```

Vagrant environment in deploy pub has been updated accordingly: https://github.com/artefactual/deploy-pub/pull/9.

### CODE REVIEW

**Comment by hakamine** [comment]
Didn't the playbook break when not running freshclam before starting clamav on a fresh (new) install?  I think I tried before (to remove freshclam to speed up the install) but had to put it back (the clamav service couldn't start because the virus db was missing IIRC)

**Comment by sevein** [comment]
That's right, thank you! Apparently the service module doesn't report the error but I'm definitely seeing it when trying to start clamav-daemon manually. Thanks, I'll add it again.

**Comment by hakamine** [comment]
Thank you @sevein for all the fixes and clean-up.
I tried to use the role to install AM on a (non-vagrant) VM, but I am having some issues. I will troubleshoot and add fixes to this PR if necessary

**Comment by sevein** [comment]
It should be fixed now.

**Comment by sevein** [comment]
:+1:

**Comment by hakamine** [comment]
:+1: I was able to confirm it worked on a non-vagrant VM install. Will merge.

**Comment by sevein** [comment]
Yay!

**Pull request merged**
