### PR TITLE
Add become_flag=-E to git clone tasks

### PR DESCRIPTION
**Pull request by mamedin**
Connects to #294

### CODE REVIEW

**Comment by scollazo** [comment]
I think it would be better to avoid touching the playbook, and configuring become flags as part of ansible.cfg when needed:

https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-become-flags

**Comment by scollazo** [comment]
@mamedin also, could you add the reason of this change to the commit message ? (not to the subject line, of course! )

**Comment by mamedin** [comment]
> I think it would be better to avoid touching the playbook, and configuring become flags as part of ansible.cfg when needed:
> 
> https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-become-flags

But using ANSIBLE_BECOME_FLAGS="-E" for all the role tasks could break something.

**Comment by mamedin** [comment]
> @mamedin also, could you add the reason of this change to the commit message ? (not to the subject line, of course! )

Done!

**Review by scollazo — APPROVED** [review]

**Pull request merged**
