### PR TITLE
Create needed directories as part of pipeline

### LINKED ISSUE #133: File tasks break when archivematica_src_install_ss set to false
When `archivematica_src_install_ss` is set to `false`, parent directories like:

/var/lib/archivematica
https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/ss-main.yml#L104

/etc/archivematica
https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/ss-main.yml#L127

and
/var/archivematica
https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/ss-main.yml#L119

are not created. Hence file operations further down the playbook break, as in:
https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/pipeline-websrv-gunicorn.yml#L19

https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/automation-tools.yml#L22

and
https://github.com/artefactual-labs/ansible-archivematica-src/blob/qa/1.7.x/tasks/pipeline-osconf.yml#L53

### PR DESCRIPTION
**Pull request by scollazo**
Closes #133

Also, removed archivematicadashboard user creation

### CODE REVIEW

**Comment by scollazo** [comment]
This should also be merged in stable/1.6.x

**Comment by sevein** [comment]
@scollazo the target of this PR is stable/1.6.x, does it need to be changed?

**Comment by scollazo** [comment]
Sorry, I wanted to say qa/1.7, stable  is the target of the pr

**Review by sevein — APPROVED** [review]
Thanks for doing this.

If this fix in qa/1.7.x is significantly different (e.g. cherry-pick doesn't bring the commit clearnly) I'd suggest to submit a new PR for it.

**Review by hakamine — CHANGES_REQUESTED** [review]
I think the changes in this PR are not required for stable/1.6.x, I have made pipeline-only (no SS) deployments with the current role without these issues. Could it be that the problems mentioned in #133 occur only in qa/1.7.x?
The removal of the archivematicadashboard user creation part is a good thing though.

**Comment by scollazo** [comment]
Closed in behalf of #144

**Comment by sevein** [comment]
@scollazo, can the branch be deleted?

**Pull request closed without merging**
