### PR TITLE
git: Set Fixity src dir as safe dir

### PR DESCRIPTION
**Pull request by mamedin**
Connects to:

 https://github.com/artefactual-labs/ansible-archivematica-src/issues/366

### CODE REVIEW

**Comment by mamedin** [comment]
Same git issue for Fixity and same fix.

**Review by DavidHume-ArtefactualSystems — COMMENTED** [review]
@mamedin - for previous AM fix (AM and SS directories), you also had
  **become_flags: "-E"**
  what does that do - "preserve environment"?, or something else?
  
  Assuming it is that or something not similarly required to apply to _fixity_ directory, then otherwise this change looks good / consistent.

**Comment by mamedin** [comment]
@DavidHume-ArtefactualSystems it depends on the user that runs the clone in the next task. For fixity using `become_flags=-E` fails. 

* Using `become_flags=-E` adds the git safe-dir setting to the ansible_user (artefactual in our deployments)
* No using `become_flags=-E` adds the git safe-dir setting to the root user (because we are running the role with become=yes)

**Comment by DavidHume-ArtefactualSystems** [comment]
> 

Thanks @mamedin - then per that explanation, looks right to me.

**Review by DavidHume-ArtefactualSystems — APPROVED** [review]

**Comment by mamedin** [comment]
Cherry-picked to:

* stable/1.12.x
* stable/1.13.x
* dev/1.13.x-xenial
* wip/centos8

**Pull request merged**
