### PR TITLE
Add am-devtools setup

### PR DESCRIPTION
**Pull request by Hwesta**
Install archivematica-devtools into the vagrant home directory.

### CODE REVIEW

**Comment by hakamine** [comment]
A question: would it be a good thing to install archivematica-devtools by default (i.e., in all installations, not only in development VMs) ? 
Also, user "vagrant" is assumed (implying this is running on a vagrant VM). I think it'd be good to try to make it more generic (so it can be used in non-vagrant installations)

**Comment by Hwesta** [comment]
> A question: would it be a good thing to install archivematica-devtools by default (i.e., in all installations, not only in development VMs) ? 

Possibly? I would use it, but it is *dev*tools. @jhsimpson?

> Also, user "vagrant" is assumed (implying this is running on a vagrant VM). I think it'd be good to try to make it more generic (so it can be used in non-vagrant installations)

I agree, it would be better if it didn't assume vagrant. I wasn't sure how to tell the command to run as the non-sudo user of ansible.

**Comment by mistydemeo** [comment]
> Possibly? I would use it, but it is devtools. @jhsimpson?

I think it's probably better not to distribute these as part of the default config. Is it possible to have multiple profiles for Ansible playbooks? I'm wondering if we could have a "developer" profile with a few differences, including installing the devtools.

**Comment by hakamine** [comment]
Addressed in https://github.com/artefactual-labs/ansible-role-archivematica-src/pull/21 by adding a role variable that allows to choose to install or not (default: no)

**Pull request closed without merging**
