### PR TITLE
git: Set AM and SS src dirs as safe dirs

### PR DESCRIPTION
**Pull request by mamedin**
Connects to https://github.com/artefactual-labs/ansible-archivematica-src/issues/366

### CODE REVIEW

**Comment by mamedin** [comment]
The 2 new tasks creates the following fire in the `ansible_ssh_user` home directory:

```
artefactual@shibu-am:~$ cat .gitconfig
[safe]
	directory = /opt/archivematica/archivematica-storage-service
	directory = /opt/archivematica/archivematica
```

And it allows to clone the src directories as `ansible_ssh_user`.

**Review by scollazo — APPROVED** [review]
LGTM

**Comment by mamedin** [comment]
Thanks Santi, but I'm going to ask for a new CR in a few minutes, because the last change was adding the same directories on every role run to the .gitconfig file. So, I'm adding an additional task to get the directories included in .gitconfig, and it will only add the SS or AM src directory in case it was not already included.

**Review by hakamine — APPROVED** [review]
LGTM. I think it also needs to be cherry-picked to the stable branch(es) (stable/1.13.x at least)

**Comment by mamedin** [comment]
Cherry-picked to:



* stable/1.13.x: https://github.com/artefactual-labs/ansible-archivematica-src/commit/a7efe5482cf3ee2a82748ab53377ff93770b5f30

* dev/1.13.x-xenial: https://github.com/artefactual-labs/ansible-archivematica-src/commit/caf9d88e3608cdfe3e506dbcadb53df0c790b694

* stable/1.12.x: https://github.com/artefactual-labs/ansible-archivematica-src/commit/47fdf70d1b7fc42da500fae35e7a4c06fe65c421

* stable/1.11.x: https://github.com/artefactual-labs/ansible-archivematica-src/commit/500e1ca39543b3be869ca2ef6054f63e75a610b1

**Pull request merged**
