### PR TITLE
Added tasks to install MediaConch 16.12

### PR DESCRIPTION
**Pull request by jrwdunham**
Cp. https://github.com/artefactual-labs/ansible-archivematica-src/pull/66

### CODE REVIEW

**Comment by sevein** [comment]
I would suggest to create a new `pipeline-deps-mediaconch.yml` play and include it from `pipeline-deps.yml` using the `include` keyword. It could be not necessary if we follow [Justin's suggestion](https://github.com/artefactual-labs/ansible-archivematica-src/pull/66#issuecomment-245463389).

You shouldn't rely on paths like `/home/vagrant/downloads` as this role is also used in production environments. I think that `tmp_dest` in the `get_url` module could help you with that.

Minor style issue: we always name tasks, quote values, avoid inline task attributes and keep consistent indentation.  E.g.:

```yml
- file: path=/home/vagrant/downloads/ state=directory mode=0755
  tags:
      - mediaconch
```

... should look like:

```yml
- file:
  path: "/home/vagrant/downloads/"
  state: "directory"
  mode: "0755"
  tags:
    - "mediaconch"
```

**Comment by jrwdunham** [comment]
@sevein I believe I've addressed your comments. I've also rebased on master.

**Comment by sevein** [comment]
Cool, thanks! /CC @jhsimpson

**Comment by hakamine** [comment]
Would it be better to use the osdeps files in archivematica 1.6.x or newer to specify these package dependencies in the archivematica repository instead of this ansible role repository?

**Comment by sevein** [comment]
> Would it be better to use the osdeps files in archivematica 1.6.x or newer to specify these package dependencies in the archivematica repository instead of this ansible role repository?

I think that makes sense, Héctor.

**Comment by sevein** [comment]
Can we point to remote debs from osdeps, @hakamine?

I've learned today that I also had to install libmms0 and libjansson4 manually, bundled by trusty.

```
- sudo apt-get install libmms0 libjansson4
- wget https://mediaarea.net/download/binary/libzen0/0.4.35/libzen0_0.4.35-1_amd64.xUbuntu_14.04.deb
- sudo dpkg -i libzen0_0.4.35-1_amd64.xUbuntu_14.04.deb
- wget https://mediaarea.net/download/binary/libmediainfo0/0.7.94/libmediainfo0_0.7.94-1_amd64.xUbuntu_14.04.deb
- sudo dpkg -i libmediainfo0_0.7.94-1_amd64.xUbuntu_14.04.deb
- wget https://mediaarea.net/download/binary/mediaconch/17.03/mediaconch_17.03-1_amd64.xUbuntu_14.04.deb
- sudo dpkg -i mediaconch_17.03-1_amd64.xUbuntu_14.04.deb
```

**Review by sevein — CHANGES_REQUESTED** [review]
So we may be just moving this to osdeps and this PR may need to be closed. @hakamine can you discuss with @jrwdunham?
If this PR is finally going to be merged in some form we'll also need to update its target to `qa/1.7.x`.

**Comment by sevein** [comment]
@jrwdunham moved the deps to osdeps!

**Pull request closed without merging**
