### PR TITLE
Py3: stop using iteritems

### LINKED ISSUE #196: Problem: py3 compatibility issue in Jinja2 templates
There are a number of templates that make use of Python2-only use dict's old built-in `iteritems`. This method was removed in Python3 so we should probably use `items` instead.

I've seen this causing the following error:

```
TASK [artefactual.archivematica-src : Add storage service gunicorn systemd env file] ***********************************************************************
fatal: [am-local]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}
	to retry, use: --limit @/Users/jesus/deploy-pub/playbooks/archivematica-xenial/singlenode.retry
```

### PR DESCRIPTION
**Pull request by sevein**
This closes #196.

### CODE REVIEW

**Comment by hakamine** [comment]
Will it still work under python 2.x? In python 2.x, `iteritems` returns an iterator, while `items` returns a list 

( Related info: https://stackoverflow.com/questions/13998492/iteritems-in-python )

**Comment by sevein** [comment]
I think that it should be ok. The iterator would be more efficient because it'd retrieve the values one at at time but that's not a problem here.

**Comment by sevein** [comment]
```
~ $ python2 -c "for k, v in {1:2, 3:4, 5:6}.items(): print('{} => {}'.format(k, v))"
1 => 2
3 => 4
5 => 6
~ $ python3 -c "for k, v in {1:2, 3:4, 5:6}.items(): print('{} => {}'.format(k, v))"
1 => 2
3 => 4
5 => 6
```

**Review by hakamine — APPROVED** [review]

**Comment by sevein** [comment]
Thank you!

**Pull request merged**
