### PR TITLE
Add xenial support

### PR DESCRIPTION
**Pull request by scollazo**
Reused @hakamine's work for Redhat/systemd, and extended it to Ubuntu 16.04

For now, this can be tested using am and ss branches dev/xenial-support

### CODE REVIEW

**Comment by scollazo** [comment]
Tested with centos 7 , and nothing broke.

**Comment by sevein** [comment]
@scollazo this is looking really good, thanks. If it's work in progress (e.g. you're still testing) should we use the `work-in-progress` label?

**Comment by scollazo** [comment]
This is working for me, the only part I'm fighting against is the acceptance-test install, as tightvncserver refuses to start on ubuntu 16.04.

Wich tag shold I use for requesting CR?

**Comment by sevein** [comment]
> Wich tag shold I use for requesting CR?

I think having a PR submitted should be enough.

**Comment by sevein** [comment]
@scollazo, do you want to submit PRs for https://github.com/artefactual/archivematica/compare/qa/1.x...dev/xenial-support and https://github.com/artefactual/archivematica-storage-service/compare/qa/0.x...dev/xenial-support?

One more question, does `deb [arch=amd64] http://packages.archivematica.org/1.6.x/ubuntu-externals trusty main` work in 16.04?

**Comment by scollazo** [comment]
@sevein yes, in order for archivematica be installed on xenial, new Ubuntu-16.json files needs to be added to osdeps/ , on both am and ss.

And yes, the ubuntu trusty repo works for xenial too.

**Review by sevein — APPROVED** [review]
LGTM.

> the only part I'm fighting against is the acceptance-test install, as tightvncserver refuses to start on ubuntu 16.04

Perhaps you should merge this PR now and file an issue to deal with that later. As you prefer. If you end up making new changes to this PR it should be reviewed again.

**Comment by scollazo** [comment]
Merged into stable/1.6.x as 823451e3, a328593c and eded96e9a2

**Pull request merged**
