### PR TITLE
Add clearing the storage service DB (rev)

### PR DESCRIPTION
**Pull request by hakamine**

### CODE REVIEW

**Comment by Hwesta** [comment]
I'd prefer if resetting the SS was separate from resetting AM, since I tend to reset them at different times, but I'm flexible if others disagree.

**Comment by hakamine** [comment]
Let's keep those separate then. Would you mind if I change the var name from archivematica_src_reset_all to  archivematica_src_reset_am_all ? In order to avoid confusion.

**Comment by Hwesta** [comment]
Sounds reasonable.

**Comment by hakamine** [comment]
Fixed. Will merge.

**Pull request merged**
